name: CI on Push and Pull Request

on: [push, pull_request]

jobs:

  Android:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android
      run: |
        cd Blank
        nuget restore
        cd Blank.Android
        msbuild Blank.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Blank/Blank.Android/bin/Debug/*.apk"
        
  iOS_Simulator:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS Simulator
      run: |
        cd Blank
        nuget restore
        msbuild Blank.iOS/Blank.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
        
  iOS_Device:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS Device
      run: |
        cd Blank
        nuget restore
        msbuild Blank.iOS/Blank.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhone /p:Configuration=Debug
    - name: Create a Release IPA
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Blank/Blank.iOS/bin/iPhone/Debug/*.ipa"
